### ISSUE TITLE
Keyphrases (topics) are missing from CSV exports

### ISSUE THREAD

**Issue by hammady** [rayyansys/rayyan-formats-core#10]
Add a new column definition "keywords" to the CSV format in import/export.
Multiple keywords would be separated by semi colons. Document this in the format description.

**Comment by kohrVid** [comment]
I've just [raised a PR for this](https://github.com/rayyansys/rayyan-formats-core/pull/14). I'm a little unclear about the documentation needed for the column. Is it enough to just add the column to the CSV `description` or do we want to tell users how to format the column (as the use of semicolons might not be intuitive for some)?

**Comment by hammady** [comment]
> Is it enough to just add the column to the CSV `description` or do we want to tell users how to format the column (as the use of semicolons might not be intuitive for some)?

Yes, adding the column name to the description is one part, then we need to tell them how to specify multiple keywords (in the description too).
